default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  socket: /tmp/mysql.sock


development:
  <<: *default
  database: daily_report_development

test:
  <<: *default
  database: daily_report_test

production:
	adapter: mysql2				
  encoding: utf8
  username: root
  password:	91tan4ev91
  socket: /tmp/mysql.sock
  database: daily_report_production